export const ON_REGISTER_INPUT_CHANGE = "ON_REGISTER_INPUT_CHANGE"
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED"
export const VERIFY_USER = "VERIFY_USER"